app:
  id: movies
  name: Movies
  info: "Movies Sample App"
  
server:
  port: 5050
      
#movies:
      
spring:
  datasource:
    url: "jdbc:mysql://localhost/movies?verifyServerCertificate=false&useSSL=true&reconnect=true"
    username: root
    password: jsimao
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:postgresql://localhost/ei_movies
    #username: postgres
  jpa:
    generate-ddl: true
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto : update
  servlet: #boot2
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    contentnegotiation:
      favor-path-extension: false
  banner:
    location : classpath:banner-movies.txt
    #image.location : /static/img/einnovator.png
    #text: > Einnovator Sample - Movie
    #renderer: http://patorjk.com/software/taag/#p=display&f=Big&t=%3E%20Einnovator Sample%20%20-%20Movies
  rabbitmq:
    host : "localhost"
    #host: rabbitmq.einnovator.org
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh
    #virtualHost: einnovator
    
                
banner: #boot1
    location : classpath:banner-movies.txt
    #image.location : /static/img/einnovator.png
    #text: einnovator | movies
    #renderer: http://patorjk.com/software/taag/#p=display&f=Big&t=einnovator%20%7C%20CMS

sso:
  server : https://sso.einnovator.org
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.einnovator.org
  amqp:
    notifications-queue: movies

documents:
  server: https://documents.einnovator.org
  files:
    root: /.movies/
  
social:
  server: https://social.einnovator.org
  
ui:
  links:
    cdn: http://cdn.einnovator.org
    sso: http://sso.einnovator.org
    notifications: http://notification.einnovator.org

