app:
  id: movies
  name: Movies
  info: "Movies Sample App"
  
server:
  port: 5050
      
#movies:
      
spring:
  datasource:
    #url: "jdbc:mysql://*****/movies?verifyServerCertificate=false&useSSL=true&reconnect=true"
    username: root
    #password: ****
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto : update
  servlet: #boot2
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    contentnegotiation:
      favor-path-extension: false
  banner:
    location : classpath:banner-movies.txt
  rabbitmq:
    host: rabbitmq.sandbox.einnovator.org
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh
    
                
banner: #boot1
    location : classpath:banner-movies.txt

sso:
  server : https://sso.sandbox.nativex.cloud
  client-id: application
  client-secret: application$123
  registration:
    auto: true
    roles:
    - name: "Movie Manager"
      global: true
    - name: "People Manager"
      global: true

notifications:
  server: https://notifications.sandbox.nativex.cloud
  amqp:
    notifications-queue: movies
  registration:
    auto: true
    types:
    - source-type: Movie
      action-type: Create
      description: "Do you want to receive notification when a Movie is created ?"
      category: Movie
      mail-template:
        #resource: notifications/mail/movie.html
    - source-type: Movie
      action-type: Update
      description: "Do you want to receive notification when a Movie is updated ?"
      category: Movie
      mail-template:
        #resource: notifications/mail/movie.html
    - source-type: Movie
      action-type: Delete
      description: "Do you want to receive notification when a Movie is deleted ?"
      category: Movie
      mail-template:
        #resource: notifications/mail/movie.html
    - source-type: Person
      action-type: Create
      description: "Do you want to receive notification when a Person is created ?"
      category: Person
      mail-template:
        #resource: notifications/mail/person.html
    - source-type: Person
      action-type: Update
      description: "Do you want to receive notification when a Person is updated ?"
      category: Person
      mail-template:
        #resource: notifications/mail/person.html
    - source-type: Person
      action-type: Delete
      description: "Do you want to receive notification when a Person is deleted ?"
      category: Person
      mail-template:
        #resource: notifications/mail/person.html

documents:
  server: https://documents.sandbox.nativex.cloud
  files:
    root: /.movies/
  
social:
  server: https://social.sandbox.nativex.cloud
  
ui:
  links:
    cdn: http://cdn.einnovator.org
    sso: http://sso.sandbox.nativex.cloud
    notifications: http://notification.sandbox.nativex.cloud

---

spring:
  profiles: local
  datasource:
    url: "jdbc:mysql://localhost/movies?verifyServerCertificate=false&useSSL=true&reconnect=true"
    password: jsimao
  rabbitmq:
    host: localhost
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh
    
sso:
  server : http://localhost:2000
  client-id: application
  client-secret: application$123

notifications:
  server: http://localhost:2010
  amqp:
    notifications-queue: movies

documents:
  server: http://localhost:2020
  
social:
  server: http://localhost:2050
  
ui:
  links:
    cdn: http://localhost:1900
    sso: http://localhost:2000
    notifications: http://localhost:2010

---

spring:
  profiles: monitor
    
sso:
  server : http://localhost:2001

notifications:
  server: http://localhost:2011

documents:
  server: http://localhost:2021
  
social:
  server: http://localhost:2051

  
---

spring:
  profiles: ei

sso:
  server : https://sso.einnovator.org
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.einnovator.org


documents:
  server: https://documents.einnovator.org

social:
  server: https://social.einnovator.org
  
ui:
  links:
    cdn: http://cdn.einnovator.org
    sso: http://sso.einnovator.org
    notifications: http://notification.einnovator.org

---

spring:
  profiles: mysandbox
 
sso:
  server : https://sso.mydomain.sandbox.nativex.cloud
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.mydomain.sandbox.nativex.cloud
  amqp:
    notifications-queue: movies

documents:
  server: https://documents.mydomain.sandbox.nativex.cloud
  files:
    root: /.movies/
  
social:
  server: https://social.mydomain.sandbox.nativex.cloud
  
ui:
  links:
    cdn: http://cdn.mydomain.sandbox.nativex.cloud
    sso: http://sso.mydomain.sandbox.nativex.cloud
    notifications: http://notification.mydomain.sandbox.nativex.cloud
  